//@flow
export const REQUEST_TRACKLIST = 'REQUEST_TRACKLIST';
export const RECEIVE_TRACKLIST = 'RECEIVE_TRACKLIST';

export const REQUEST_GET_PLAYER = 'REQUEST_GET_PLAYER';
export const RECEIVE_PLAYER = 'RECEIVE_PLAYER';
export const TRACK_START_PLAYING = 'TRACK_START_PLAYING';
export const TRACK_FINISHED_PLAYING = 'TRACK_FINISHED_PLAYING';
export const TRACK_RESUME_PLAYING_PAUSED = 'TRACK_RESUME_PLAYING_PAUSED';
export const TRACK_PAUSE = 'TRACK_PAUSE';
export const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME';

export const UPDATE_VOLUME = 'UPDATE_VOLUME';
