export const REQUEST_TRACKLIST = 'REQUEST_TRACKLIST';
export const RECEIVE_TRACKLIST = 'RECEIVE_TRACKLIST';

export const REQUEST_TRACK_PLAY = 'REQUEST_TRACK_PLAY';
export const TRACK_PLAY_START = 'TRACK_PLAY_START';
export const REQUEST_TRACK_PAUSE = 'REQUEST_TRACK_PAUSE';
export const TRACK_PAUSED = 'TRACK_PAUSED';
